### ISSUE TITLE
getDetailedStatusReport not working

### ISSUE THREAD

**Issue by perelman** [constantcontact/java-sdk#65]
Hi all
I try to get the DetailedStatusReport for activity to poll the activity status until it is completed.
I am using getDetailedStatusReport and getting errors from constantContact. 

RawApiRequestError [errorKey=query.param.invalid, errorMessage=The query parameter id is not supported.]
RawApiRequestError [errorKey=url, errorMessage=https://api.constantcontact.com/v2/activities?type=ADD_CONTACTS&id=9420c040-fdc0-11e4-9f58-d4ae527548e1]

Look like the id parameter should be in the url path and not in query args

By the way do addContacts command check for the status of the activity before returning the Result or should i handle it myself?
Thanks!
Yuval Perelman

**Comment by csciuto** [comment]
Fixed in https://github.com/constantcontact/java-sdk/pull/67

**Comment by egaiter** [comment]
Hi Yuval,

With the addContacts method, the status is not included in the response. With the updates merged in #67 you should now have the ability to properly use getDetailedStatus report. I do also want to mention that the parameters for getSummaryReport and getDetailedStatus report have been changed. The new formats for calling these methods are:
getSummaryReport() -- Get a list of all activities
getSummaryReport(String status, String type) -- Get a list of activities filtered by status, type, or both. This accepts null parameters.
getDetailedStatusReport(String id) -- Get the details for a specific activity. Also note that this now returns DetailedStatusReport instead of List<DetailedStatusReport>.

If you've got any questions, please let us know!

Sincerely,
Elijah Gaiter
API Support Engineer
Constant Contact
